export const charSkills: Array<any> = [
  {szakertelem: 'Atlétika', csoport: 'fizikai', fcname: 'karFizAll'},
  {szakertelem: 'Futás', csoport: 'fizikai', fcname: 'karFizEro'},
  {szakertelem: 'Úszás', csoport: 'fizikai', fcname: 'karFizEro'},
  {szakertelem: 'Búvárkodás', csoport: 'fizikai', fcname: 'karFizAll'},
  {szakertelem: 'Lopakodás', csoport: 'fizikai', fcname: 'karFizUgy'},
  {szakertelem: 'Akrobatika', csoport: 'fizikai', fcname: 'karFizUgy'},
  {szakertelem: 'Szabadulás', csoport: 'fizikai', fcname: 'karFizUgy'},
  {szakertelem: 'Mászás', csoport: 'fizikai', fcname: 'karFizUgy'},
  {szakertelem: 'Ágyúk', csoport: 'harci', fcname: 'karAsztUgy'},
  {szakertelem: 'Dobófegyverek', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Éles fegyverek', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Fegyvertelen harc', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Géppisztolyok', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Lőfegyverek', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Kiberfegyverek', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Korbácsok', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Lézerfegyverek', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Pisztolyok', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Puskák', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Rakétavetők', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Rohampuskák', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Sörétes puskák', csoport: 'harci', fcname: 'karFizUgy'},
  {szakertelem: 'Szálfegyverek', csoport: 'harci', fcname: 'karFizEro'},
  {szakertelem: 'Tompa fegyverek', csoport: 'harci', fcname: 'karFizEro'},
  {szakertelem: 'Víz alatti harc', csoport: 'harci', fcname: 'karFizEro'},
  {szakertelem: 'Autó', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Helikopter', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Léghajó', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Légpárnás', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Motor', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Motoros hajó', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Nagy hajó', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Rakétahajtású jármű', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Repülő', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Tengeralattjáró', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Vitorlás', csoport: 'jármű', fcname: 'karFizGyo'},
  {szakertelem: 'Auraolvasás', csoport: 'mágikus', fcname: 'karAsztUgy'},
  {szakertelem: 'Idézés', csoport: 'mágikus', fcname: 'karAsztAll'},
  {szakertelem: 'Asztrális projekció', csoport: 'mágikus', fcname: 'karMagia'},
  {szakertelem: 'Varázslás', csoport: 'mágikus', fcname: 'karAsztEro'},
  {szakertelem: 'Alkímia', csoport: 'mágikus', fcname: 'karAsztUgy'},
  {szakertelem: 'Varázsvédelem', csoport: 'mágikus', fcname: 'karMagia'},
  {szakertelem: 'Semlegesítés', csoport: 'mágikus', fcname: 'karMagia'},
  {szakertelem: 'Csapatvezetés', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Etikett', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Megfélelmítés', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Tanítás', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Tárgyalás', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Vallatás', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Idomítás', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Megszemélyesítés', csoport: 'szociális', fcname: 'karAsztAll'},
  {szakertelem: 'Mesterség', csoport: 'szociális', fcname: 'karAsztGyo'},
  {szakertelem: 'Elrejtés', csoport: 'szociális', fcname: 'karAsztGyo'},
  {szakertelem: 'Navigáció', csoport: 'szociális', fcname: 'karAsztGyo'},
  {szakertelem: 'Érzékelés', csoport: 'szociális', fcname: 'karAsztGyo'},
  {szakertelem: 'Nyomolvasás', csoport: 'szociális', fcname: 'karAsztGyo'},
  {szakertelem: 'Biotechnika', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Elektronika', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Robbantás', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Számítógép', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Mechanika', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Kémia', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Kibertechnológia', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Programozás', csoport: 'technikai', fcname: 'karAsztUgy'},
  {szakertelem: 'Érdeklődési körök', csoport: 'ismeret', fcname: 'karAsztUgy'},
  {szakertelem: '6. világbeli ism.', csoport: 'ismeret', fcname: 'karAsztUgy'},
  {szakertelem: 'Háttér ismeretek', csoport: 'ismeret', fcname: 'karAsztUgy'},
  {szakertelem: 'Iskolai ismeretek', csoport: 'ismeret', fcname: 'karAsztUgy'},
  {szakertelem: 'Utcai ismeretek', csoport: 'ismeret', fcname: 'karAsztUgy'},
  {szakertelem: 'Nyelvismeret', csoport: 'nyelvi', fcname: 'karAsztUgy'},
  {szakertelem: 'Írás/olvasás', csoport: 'nyelvi', fcname: 'karAsztUgy'},
];
