export const charSkills: Array<any> = [
  {faName: 'activeSkills', szakertelem: 'Atlétika', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Futás', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Úszás', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Búvárkodás', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Lopakodás', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Akrobatika', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Szabadulás', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Mászás', group: 'Fizikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Ágyúk', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Dobófegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Éles fegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Fegyvertelen harc', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Géppisztolyok', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Lőfegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Kiberfegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Korbácsok', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Lézerfegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Pisztolyok', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Puskák', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Rakétavetők', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Rohampuskák', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Sörétes puskák', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Szálfegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Tompa fegyverek', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Víz alatti harc', group: 'Harci', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Autó', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Helikopter', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Léghajó', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Légpárnás', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Motor', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Motoros hajó', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Nagy hajó', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Rakétahajtású Jármű', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Repülő', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Tengeralattjáró', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Vitorlás', group: 'Jármű', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Auraolvasás', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Idézés', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Asztrális projekció', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Varázslás', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Alkímia', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Varázsvédelem', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Semlegesítés', group: 'Mágikus', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Csapatvezetés', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Etikett', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Megfélelmítés', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Tanítás', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Tárgyalás', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Vallatás', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Idomítás', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Megszemélyesítés', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Mesterség', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Elrejtés', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Navigáció', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Érzékelés', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Nyomolvasás', group: 'Szociális', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Biotechnika', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Elektronika', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Robbantás', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Számítógép', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Mechanika', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Kémia', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Kibertechnológia', group: 'Technikai', legend: 'Aktív'},
  {faName: 'activeSkills', szakertelem: 'Programozás', group: 'Technikai', legend: 'Aktív'},
  {faName: 'knowledgeSkills', szakertelem: 'Érdeklődési körök', group: 'Ismeret', legend: 'Ismeret'},
  {faName: 'knowledgeSkills', szakertelem: '6. világbeli ism.', group: 'Ismeret', legend: 'Ismeret'},
  {faName: 'knowledgeSkills', szakertelem: 'Háttér ismeretek', group: 'Ismeret', legend: 'Ismeret'},
  {faName: 'knowledgeSkills', szakertelem: 'Iskolai ismeretek', group: 'Ismeret', legend: 'Ismeret'},
  {faName: 'knowledgeSkills', szakertelem: 'Utcai ismeretek', group: 'Ismeret', legend: 'Ismeret'},
  {faName: 'languageSkills', szakertelem: 'Nyelvismeret', group: 'Beszéd', legend: 'Nyelvi'},
  {faName: 'languageSkills', szakertelem: 'Írás/olvasás', group: 'Írott', legend: 'Nyelvi'},
  {faName: 'languageSkills', szakertelem: 'Anyanyelvi beszéd', group: 'Beszéd', legend: 'Nyelvi', show: false},
  {faName: 'languageSkills', szakertelem: 'Anyanyelvi Í/O', group: 'Írott', legend: 'Nyelvi', show: false},
];
