export interface Resources {
  basekarma: number,
  gainedkarma: number,
  karmaonattr: number,
  karmaonskills: number,
  karmaonmoney: number,
  gainedmoney: number,
  karmaonmagic: number,
  magiconspells: number,
  magiconspirits: number,
  magiconartifacts: number,
  moneyonwapons: number,
  moneyontools: number,
  moneyoncyber: number,
  moneyonsoftware: number,
  moneyonrides: number,
  moneyonartifacts: number,
}

export const resources: Array<any> = [
  {nev: 'Induló Karma', csoport: 'Karma', fcname: 'basekarma', maxValue: 250, inputfield: true},
  {nev: 'Kapott Karma', csoport: 'Karma', fcname: 'gainedkarma', maxValue: 50, inputfield: true},
  {nev: 'Tulajdonságok (3karma/1pont)', csoport: 'Karma', fcname: 'karmaonattr', lepes:3, maxValue: 50},
  {nev: 'Szakértelmek (2karma/1pont)', csoport: 'Karma', fcname: 'karmaonskills', lepes:2, maxValue: 60},
  {nev: 'Erőforrások (1karma/6000cred)', csoport: 'Karma', fcname: 'karmaonmoney', maxValue: 150},
  {nev: 'Szerzett erőforrások', csoport: 'Karma', fcname: 'gainedmoney', inputfield: true},
  {nev: 'Mágia pontok (2karma/1pont)', csoport: 'Karma', fcname: 'karmaonmagic', lepes:2, maxValue: 60},
  {nev: 'Varázslatok', csoport: 'Mágia', fcname: 'magiconspells'},
  {nev: 'Szellemek', csoport: 'Mágia', fcname: 'magiconspirits'},
  {nev: 'Mágikus eszközök', csoport: 'Mágia', fcname: 'magiconartifacts'},
  {nev: 'Fegyverek', csoport: 'Erőforrások', fcname: 'moneyonwapons'},
  {nev: 'Felszerelések', csoport: 'Erőforrások', fcname: 'moneyontools'},
  {nev: 'Kiberverek', csoport: 'Erőforrások', fcname: 'moneyoncyber'},
  {nev: 'Programok', csoport: 'Erőforrások', fcname: 'moneyonsoftware'},
  {nev: 'Járművek', csoport: 'Erőforrások', fcname: 'moneyonrides'},
  {nev: 'Mágikus eszközök', csoport: 'Erőforrások', fcname: 'moneyonartifacts'},
];
