export interface Char {
  id: string,
  creatorID: string,
  creatorName: string,
  teljesnev: string,
  becenev:string,
  alnev:string,
  testalkat:string,
  hajstilus:string,
  szakall:string,
  nem: string,
  faj:string,
  anyanyelv: string,
  magikus:string,
  spec:string,
  eletkor:string,
  magassag:string,
  testsuly:string,
  szemszin:string,
  hajszin:string,
  szorszin:string,
  borszin:string,
  felelem:string,
  osztonzo:string,
  gyulolet:string,
  kedvenc:string,
  irtozat:string,
  vonzalom:string,

}
