export interface Details {
  //szöveges
  teljesnev: string,
  becenev:string,
  alnev:string,
  testalkat:string,
  hajstilus:string,
  szakall:string,
  //értékválasztó
  nem: string,
  faj:string,
  anyanyelv: string,
  magikus:string,
  spec:string,
  eletkor:string,
  magassag:string,
  testsuly:string,
  //szín
  szemszin:string,
  hajszin:string,
  szorszin:string,
  borszin:string,
  // hosszú szöveg
  felelem:string,
  osztonzo:string,
  gyulolet:string,
  kedvenc:string,
  irtozat:string,
  vonzalom:string,
};

export const details: Array<any> = [
  {nev: 'Teljes név', fcname:'teljesnev', type: 'text', megjegyz: 'Amit a Sírodra vésnek...'},
  {nev: 'Becenév', fcname:'becenev', type: 'text', megjegyz: 'Ahogy a Haverok ismernek...'},
  {nev: 'Álnév', fcname:'alnev', type: 'text', megjegyz: 'Az Alvilágban így hívnak...'},
  {nev: 'Nem', fcname:'nem', type: 'select', listname:'Nem', megjegyz:'De! Vagy mit tudom én!?'},
  {nev: 'Faj', fcname:'faj', type: 'select', listname:'Fajok', megjegyz:'Fajta, te paraszt!'},
  {nev: 'Anyanyelv', fcname:'anyanyelv', type: 'inpselect', listname:'Nyelvek', megjegyz:'Ha kitolod, levágjuk...'},
  {nev: 'Mágikus Út', fcname:'magikus', type: 'select', listname:'Hagyomany', megjegyz:'Vagy a króm, vagy ez.'},
  {nev: 'Specializáció', fcname:'spec', type: 'select', listname:'Utak'},
  {nev: 'Életkor (év)', fcname:'eletkor', type: 'number'},
  {nev: 'Magasság (cm)', fcname:'magassag', type: 'number'},
  {nev: 'Testsúly (kg)', fcname:'testsuly', type: 'number'},
  {nev: 'Testalkat', fcname:'testalkat', type: 'text', megjegyz: 'Mackós, vagy girhes?'},
  {nev: 'Szemszín', fcname:'szemszin', type: 'color'},
  {nev: 'Bőrszín', fcname:'borszin', type: 'color'},
  {nev: 'Hajszín', fcname:'hajszin', type: 'color'},
  {nev: 'Hajstílus', fcname:'hajstilus', type: 'text', megjegyz: 'Az Árnyak között is fontos!'},
  {nev: 'Szőrzet színe', fcname:'szorszin', type: 'color'},
  {nev: 'Szakáll stílusa', fcname:'szakall', type: 'text', megjegyz: 'Persze csak ha van :p'},
  {nev: 'Félelem', fcname:'felelem', type: 'text', megjegyz: 'Mindenki fél valamitől...'},
  {nev: 'Ösztönző', fcname:'osztonzo', type: 'text', megjegyz: 'De van, ami képes bátorítani!'},
  {nev: 'Gyűlölet', fcname:'gyulolet', type: 'text', megjegyz: 'Ne a gyűlölet vezéreljen...'},
  {nev: 'Kedvenc', fcname:'kedvenc', type: 'text', megjegyz: 'Hanem ami boldoggá tesz!'},
  {nev: 'Írtózat', fcname:'irtozat', type: 'text', megjegyz: 'Lehet, mástól kifordul a beled...'},
  {nev: 'Vonzalom', fcname:'vonzalom', type: 'text', megjegyz: 'De ennek te sem tudsz ellenállni!'},
];
